from datetime import datetime
from graph.state import CodeReviewState
from utils.helpers import count_issues_by_severity

SEVERITY_EMOJI = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}
CATEGORY_EMOJI = {"style": "🎨", "bug": "🐛", "security": "🔐"}

def _render_issues_table(issues: list[dict], category: str) -> str:
    emoji = CATEGORY_EMOJI.get(category, "📌")
    if not issues:
        return f"### {emoji} {category.title()} Issues\n\n✅ No {category} issues found.\n"

    lines = [
        f"### {emoji} {category.title()} Issues\n",
        "| Severity | Location | Description | Suggestion |",
        "|----------|----------|-------------|------------|",
    ]
    for issue in issues:
        sev_emoji = SEVERITY_EMOJI.get(issue.get("severity", "INFO"), "⚪")
        lines.append(
            f"| {sev_emoji} {issue.get('severity','?')} "
            f"| `{issue.get('line_hint','?')}` "
            f"| {issue.get('description','?')} "
            f"| {issue.get('suggestion','?')} |"
        )
    return "\n".join(lines) + "\n"

def reporter_node(state: CodeReviewState) -> CodeReviewState:
    print("📋 [Reporter] Building final report...")

    style_issues    = state.get("style_issues", [])
    bug_issues      = state.get("bug_issues", [])
    security_issues = state.get("security_issues", [])
    all_issues      = style_issues + bug_issues + security_issues
    counts          = count_issues_by_severity(all_issues)
    language        = state.get("language", "unknown").upper()
    timestamp       = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    penalty = (
        counts["CRITICAL"] * 25 + counts["HIGH"] * 15 +
        counts["MEDIUM"] * 7   + counts["LOW"] * 2
    )
    score = max(0, 100 - penalty)
    score_label = (
        "🏆 Excellent" if score >= 90 else
        "✅ Good"      if score >= 75 else
        "⚠️ Needs Work" if score >= 50 else
        "❌ Poor"
    )

    report = f"""# 🔍 Code Review Report

**Language:** {language}
**Reviewed At:** {timestamp}
**Overall Score:** {score}/100 — {score_label}

---

## 📊 Summary

| Category | Count |
|----------|-------|
| 🎨 Style | {len(style_issues)} |
| 🐛 Bugs | {len(bug_issues)} |
| 🔐 Security | {len(security_issues)} |
| **Total** | **{len(all_issues)}** |

### Severity Breakdown
| 🔴 CRITICAL | {counts['CRITICAL']} |
| 🟠 HIGH | {counts['HIGH']} |
| 🟡 MEDIUM | {counts['MEDIUM']} |
| 🔵 LOW | {counts['LOW']} |
| ⚪ INFO | {counts['INFO']} |

---

## 📝 Detailed Findings

{_render_issues_table(style_issues, "style")}
{_render_issues_table(bug_issues, "bug")}
{_render_issues_table(security_issues, "security")}

---

## 🔧 Suggested Fixed Code

{state.get("fix_suggestions", "_No fixes generated._")}

---
*Generated by Code Review Assistant | LangGraph + Groq*
"""
    print(f"   ✅ Score: {score}/100 ({score_label})")
    return {**state, "final_report": report}